# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bc1e313ab05be16e0cb23c3d30a61e43def6fc3b6c2db4228ff084f617e579a46a5f6d06a0578c2cd201b19f74015ec76517942c09aea0ab9a240a98730bc10

test:
  secret_key_base: 51f0def7d4eda8b26193f3cf4c08aba885874035e0ab51894a9ca952e58c9ef5b65e75d9f383284f53b2eca98f2cdcfd42dca1441cc716a0ac94807436964ee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
